### ISSUE TITLE
modRana hangs on launch at "starting modRana" screen

### ISSUE THREAD

**Issue by schmittlauch** [M4rtinK/modrana#210]
A freshly installed modRana 0.54.7-1.1 fails to fully launch on Jolla1 with SFOS 2.1.1.24, giving the following traceback:

```
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Could not find any zN.M subdirs!
[W] unknown:0 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist
[D] info:23 - INFO: Actions: Sailfish media keys initialized
[D] info:23 - INFO: KeepAlive: keep alive control initialized
[D] info:23 - INFO: Screen: screen blanking control initialized
[D] info:23 - INFO: importing the modRana Python core
[D] info:23 - INFO: starting the modRana Python core
DEBUG : argv from QML:
['-u', 'qt5', '-d', 'jolla']
DEBUG : full argv:
['modrana.py', '-u', 'qt5', '-d', 'jolla']
INFO :  == modRana Starting == 
INFO :   0.54.7
INFO :   Python 3.4.3
INFO :  * device: A Jolla device module (32.78 ms)
INFO : loading options
ERROR core.config: loading map_config.conf failed
Traceback (most recent call last):
  File "/usr/share/harbour-modrana/core/configs.py", line 178, in load_map_config
    self._map_config = ConfigObj(map_config_path)
  File "/usr/share/harbour-modrana/core/bundle/configobj/configobj.py", line 1211, in __init__
    self._load(infile, configspec)
  File "/usr/share/harbour-modrana/core/bundle/configobj/configobj.py", line 1299, in _load
    raise error
  File "<string>", line None
configobj.configobj.ParseError: Invalid line at line "22".
INFO : using PyOtherSide 1.4.0
INFO :  * gui: A Qt + QML GUI module (90.19 ms)
INFO : importing modules:
INFO :  * tracklog: Record tracklogs (514.91 ms)
INFO :  * notification: This module provides notification support. (17.82 ms)
INFO :  * projection: Projection code (lat/long to screen conversions) (25.91 ms)
INFO :  * askMenu: A module providing yes/no question dialogs (8.06 ms)
INFO :  * showOSD: Draw OSD (On Screen Display). (22.77 ms)
INFO :  * display: A platform independent display device control module (14.53 ms)
INFO :  * textEntry: A module for handling text entry. (8.36 ms)
ERROR mod.mapLayers: map layer config has no valid layers, using Mapnik fallback layer
INFO :  * mapLayers: Map layer handling (62.54 ms)
INFO :  * animatedMapView: A sample pyroute module (8.03 ms)
INFO :  * showPOI: Show POI on the map and in the menu. (25.85 ms)
INFO :  * menu: Handle menus (100.63 ms)
INFO :  * search: Search for POI (46.51 ms)
INFO :  * routeProfile: Creates a route profile (an elevation chart) (10.96 ms)
INFO :  * clickHandler: handle mouse clicks (18.59 ms)
INFO :  * example: A sample modRana module (5.92 ms)
DEBUG mod.storeTiles: tile loading debug messages state: disabled
INFO :  * storeTiles: Single-file-fs tile storage (112.16 ms)
INFO :  * positionMarker: A sample pyroute module (9.52 ms)
INFO :  * tracklogManager: Module for managing tracklogs (17.98 ms)
INFO :  * loadTracklogs: A sample pyroute module (38.91 ms)
INFO :  * stats: Handles statistics (7.96 ms)
INFO :  * voice: Handle text to speech. (10.35 ms)
INFO :  * updateTiles: Update stored map tiles. (3.88 ms)
INFO :  * mapView: Controls the view being displayed on the map (24.11 ms)
INFO :  * onlineServices: A module for talking to various online services (399.36 ms)
INFO :  * options: Handle options (81.34 ms)
INFO :  * icons: Draw icons (33.45 ms)
INFO mod.mapTiles: in memory tile cache size: 150
INFO mod.mapTiles: map folder path: /home/nemo/.local/share/harbour-modrana/maps
INFO :  * mapTiles: Display map images (570.82 ms)
INFO :  * messages: Handles messages (10.32 ms)
INFO :  * info: A modRana information handling module (16.91 ms)
INFO :  * tileserver: A modRana built-in tileserver (65.77 ms)
INFO :  * showTracklogs: draws a GPX track on the map (25.27 ms)
INFO :  * input: Handle input from keyboard, buttons, etc. (5.62 ms)
INFO :  * interfaceFeedback: A sample pyroute module (3.88 ms)
INFO :  * sketch: Sketching functionality (7.48 ms)
INFO :  * keys: A keyboard input handling module (5.83 ms)
INFO :  * markers: A module handling markers on the map. (16.39 ms)
INFO :  * location: Supplies position info from a position source (16.79 ms)
INFO :  * route: Routes (90.25 ms)
INFO core.poi_db: POI database path:
INFO core.poi_db: /home/nemo/.local/share/harbour-modrana/poi/modrana_poi.db
INFO core.poi_db: connection to POI db established
INFO :  * storePOI: Store POI data. (31.31 ms)
INFO :  * units: a unit handling module  (20.51 ms)
INFO :  * cron: A Qt 5 timing and scheduling module for modRana (18.80 ms)
INFO :  * mapData: Handle downloading of map data (75.69 ms)
INFO :  * theme: ModRana theming module (19.01 ms)
INFO :  * turnByTurn: A turn by turn navigation module. (41.69 ms)
INFO : Loaded all modules in 2710.00 ms, initialising
INFO mod.options: reloading Monav data pack list
DEBUG mod.mapTiles: automatic tile download queue size: 100
INFO core.threads: Running Thread: automaticTileDownloadWorker1 (1242559376)
INFO core.threads: Running Thread: automaticTileDownloadWorker2 (1244853136)
INFO core.threads: Running Thread: automaticTileDownloadWorker3 (1247273872)
INFO core.threads: Running Thread: automaticTileDownloadWorker4 (1249665936)
INFO core.threads: Running Thread: automaticTileDownloadWorker5 (1252447120)
INFO core.threads: Running Thread: automaticTileDownloadWorker6 (1255588752)
INFO core.threads: Running Thread: automaticTileDownloadWorker7 (1257780112)
INFO core.threads: Running Thread: automaticTileDownloadWorker8 (1260409744)
INFO core.threads: Running Thread: automaticTileDownloadWorker9 (1263006608)
INFO core.threads: Running Thread: automaticTileDownloadWorker10 (1265873808)
INFO core.threads: Running Thread: modRanaTileDownloadManager (1268528016)
INFO mod.loadTracklogs: ** making a list of available tracklogs
INFO mod.loadTracklogs: *  using this tracklog folder:
INFO mod.loadTracklogs: * /home/nemo/.local/share/harbour-modrana/tracklogs
INFO mod.loadTracklogs: *  there are 2 tracklogs available
INFO mod.loadTracklogs: **
INFO mod.mapView: switching map drag mode to default
INFO mod.mapView: switching centering disable threshold to 2048
INFO : Initialization complete in 65.86 ms
INFO : ** modRana startup timing **
INFO : # device: Jolla (jolla)
INFO : * modRana start (0 ms), 0/3883 ms
INFO : * imports done (859 ms), 859/3883 ms
INFO : * GUI creation (25 ms), 884/3883 ms
INFO : * all modules loaded (2933 ms), 3817/3883 ms
INFO : * all modules initialized (66 ms), 3883/3883 ms
INFO : ** whole startup: 3883 ms **
INFO mod.gui.qt5.qml: redirecting QML log to the Python log
INFO mod.gui.qt5.qml: screen blanking enabled
INFO mod.gui.qt5.qml: theme changed to: Silica theme (id: silica)
INFO mod.gui.qt5.qml: __init__ running
INFO mod.gui.qt5.qml: Qt5 location initialized
INFO mod.gui.qt5.qml: Qt5 GUI location provider: undefined
[D] unknown:0 - "PyOtherSide error: Traceback (most recent call last):\n\n  File \"modules/gui_modules/gui_qt5/gui_qt5.py\", line 401, in _getStartupValues\n    \"dictOfLayerDicts\" : self.modules.mapLayers.getDictOfLayerDicts(),\n\n  File \"modules/mod_mapLayers/mod_mapLayers.py\", line 130, in getDictOfLayerDicts\n    d[k] = v.dict\n\n  File \"/usr/share/harbour-modrana/core/layers.py\", line 152, in dict\n    \"type\" : self.type,\n\n  File \"/usr/share/harbour-modrana/core/layers.py\", line 46, in type\n    return self.config['type']\n\nKeyError: 'type'\n"
INFO mod.gui.qt5.qml: keeping screen on
ERROR mod.gui.qt5.qml: python error: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "modules/gui_modules/gui_qt5/gui_qt5.py", line 401, in _getStartupValues
    "dictOfLayerDicts" : self.modules.mapLayers.getDictOfLayerDicts(),

  File "modules/mod_mapLayers/mod_mapLayers.py", line 130, in getDictOfLayerDicts
    d[k] = v.dict

  File "/usr/share/harbour-modrana/core/layers.py", line 152, in dict
    "type" : self.type,

  File "/usr/share/harbour-modrana/core/layers.py", line 46, in type
    return self.config['type']

KeyError: 'type'

ERROR mod.gui.qt5.qml: python error: file:///usr/share/harbour-modrana/qml/harbour-modrana.qml:451: TypeError: Cannot read property 'hiDPI' of undefined
INFO mod.gui.qt5.qml: screen blanking disabled
```

Removing ~/.config/harbour-modrana and ~/.local/share/harbour-modrana didn't help.

**Comment by schmittlauch** [comment]
Updating to 0.54.8 solved the issue, sorry to bother you.
