### ISSUE TITLE
modrana will not start on fresh debian install

### ISSUE THREAD

**Issue by soplaris** [M4rtinK/modrana#285]
This time I downloaded modrana/master and it won't start. Did I miss some dependencies?

This is the output on debian/sid:

INFO :  == modRana Starting == 
WARNING core.paths: local version file is missing
INFO :   unknown version
INFO :   Python 2.7.16
INFO :   Debian GNU/Linux 10 (buster)
INFO core.platform_detection: ** detecting current device **
INFO core.platform_detection: * PC detected
INFO core.platform_detection: ** selected pc as device module ID **
INFO :  * device: A modRana device-specific module for PC (0.86 ms)
INFO : loading options
ERROR : exception while loading saved options
Traceback (most recent call last):
  File "./modrana.py", line 901, in _load_options
    f = open(self.paths.options_file_path, "rb")
IOError: [Errno 2] No such file or directory: '/home/ben/.modrana/options.bin'
ERROR : module: gui_gtk/gui failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/gui_modules/gui_gtk.py", line 25, in <module>
    import pygtk
ImportError: No module named pygtk
INFO : importing modules:
ERROR : module: mod_turnByTurn/turnByTurn failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_turnByTurn/__init__.py", line 1, in <module>
    from .mod_turnByTurn import getModule
  File "modules/mod_turnByTurn/mod_turnByTurn.py", line 48, in <module>
    import pango
ImportError: No module named pango
ERROR : module: mod_textEntry/textEntry failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_textEntry.py", line 26, in <module>
    import gtk
ImportError: No module named gtk
ERROR : module: mod_display/display failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_display.py", line 27, in <module>
    import gtk
ImportError: No module named gtk
INFO :  * theme: ModRana theming module (0.75 ms)
INFO :  * clickHandler: handle mouse clicks (0.19 ms)
INFO :  * mapLayers: Map layer handling (4.52 ms)
INFO mod.location: using GPSD
INFO mod.location.gpsd: location: gpsd not used, so there is no debug output to enable
INFO :  * location: Supplies position info from a position source (0.74 ms)
INFO :  * showPOI: Show POI on the map and in the menu. (0.45 ms)
INFO :  * askMenu: A module providing yes/no question dialogs (0.08 ms)
INFO :  * info: A modRana information handling module (0.43 ms)
INFO :  * example: A sample modRana module (0.08 ms)
INFO :  * notification: This module provides notification support. (0.20 ms)
INFO :  * input: Handle input from keyboard, buttons, etc. (0.07 ms)
INFO :  * stats: Handles statistics (0.11 ms)
ERROR : module: mod_menu/menu failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_menu.py", line 30, in <module>
    import gtk
ImportError: No module named gtk
ERROR : module: mod_mapTiles/mapTiles failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_mapTiles/__init__.py", line 1, in <module>
    from .mod_mapTiles import getModule
  File "modules/mod_mapTiles/mod_mapTiles.py", line 47, in <module>
    from .tile_downloader import Downloader
  File "modules/mod_mapTiles/tile_downloader.py", line 41, in <module>
    import gtk
ImportError: No module named gtk
ERROR : module: mod_tileserver/tileserver failed to load
Traceback (most recent call last):
  File "./modrana.py", line 450, in _load_module
    module = a.getModule(self, moduleName, importName)
  File "modules/mod_tileserver.py", line 42, in getModule
    return Tileserver(*args, **kwargs)
  File "modules/mod_tileserver.py", line 58, in __init__
    if self.modrana.gui.needsLocalhostTileserver():
AttributeError: 'NoneType' object has no attribute 'needsLocalhostTileserver'
INFO :  * units: a unit handling module  (0.21 ms)
ERROR : module: mod_tracklog/tracklog failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_tracklog.py", line 32, in <module>
    import gtk
ImportError: No module named gtk
DEBUG mod.storeTiles: tile loading debug messages state: disabled
ERROR mod.storeTiles: invalid tile storage type was requested and will be ignored: None
INFO :  * storeTiles: Single-file-fs tile storage (3.99 ms)
INFO :  * search: Search for POI (0.31 ms)
INFO :  * onlineServices: A module for talking to various online services (2.22 ms)
ERROR : module: mod_showTracklogs/showTracklogs failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_showTracklogs.py", line 28, in <module>
    import gtk
ImportError: No module named gtk
INFO :  * mapData: Handle downloading of map data (0.83 ms)
ERROR : module: mod_routeProfile/routeProfile failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_routeProfile.py", line 26, in <module>
    import cairo
ImportError: No module named cairo
INFO core.poi_db: POI database path:
INFO core.poi_db: /home/ben/.modrana/poi/modrana_poi.db
INFO core.poi_db: connection to POI db established
INFO :  * storePOI: Store POI data. (0.56 ms)
ERROR : module: mod_markers/markers failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_markers.py", line 23, in <module>
    from core.color import Color
  File "/home/ben/Downloads/modrana/core/color.py", line 11, in <module>
    import gtk
ImportError: No module named gtk
INFO :  * voice: Handle text to speech. (0.11 ms)
INFO :  * route: Routes (0.77 ms)
INFO :  * projection: Projection code (lat/long to screen conversions) (0.18 ms)
ERROR : module: mod_keys/keys failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_keys.py", line 26, in <module>
    import gtk
ImportError: No module named gtk
ERROR : module: mod_icons/icons failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_icons.py", line 33, in <module>
    import gtk
ImportError: No module named gtk
INFO :  * positionMarker: A sample pyroute module (0.09 ms)
ERROR : module: mod_mapView/mapView failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_mapView.py", line 21, in <module>
    from core import color
  File "/home/ben/Downloads/modrana/core/color.py", line 11, in <module>
    import gtk
ImportError: No module named gtk
ERROR : module: mod_showOSD/showOSD failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_showOSD.py", line 26, in <module>
    import cairo
ImportError: No module named cairo
INFO :  * tracklogManager: Module for managing tracklogs (0.13 ms)
INFO :  * messages: Handles messages (0.08 ms)
INFO :  * options: Handle options (0.66 ms)
INFO :  * loadTracklogs: A sample pyroute module (0.27 ms)
ERROR : module: mod_cron/cron failed to load
Traceback (most recent call last):
  File "./modrana.py", line 448, in _load_module
    a = imp.load_module(importName, fp, pathName, description)
  File "modules/mod_cron.py", line 28, in <module>
    import gobject
ImportError: No module named gobject
INFO : Loaded all modules in 66.38 ms, initialising
Traceback (most recent call last):
  File "./modrana.py", line 1046, in <module>
    start()
  File "./modrana.py", line 1030, in start
    modrana = ModRana()
  File "./modrana.py", line 216, in __init__
    self._load_modules()
  File "./modrana.py", line 376, in _load_modules
    self._modules_loaded_pre_first_time()
  File "./modrana.py", line 499, in _modules_loaded_pre_first_time
    if self.gui.showQuitButton():
AttributeError: 'NoneType' object has no attribute 'showQuitButton'

**Comment by soplaris** [comment]
I finally found out that the python-gtk2 package was missing. Thank you for nothing!
